name: Symfony CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/php-action@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xml, ctype, iconv, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Symfony commands
        run: |
          php bin/console doctrine:migrations:migrate --no-interaction
          php bin/console cache:clear
