name: Symfony CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xml, ctype, iconv, pdo, pdo_mysql, tokenizer, json

      - name: Install Backend Dependencies
        run: |
          cd IdRecette_Back_Symfony
          composer install --no-progress --prefer-dist

      - name: Create Database
        run: |
          cd IdRecette_Back_Symfony
          php bin/console doctrine:database:create --if-not-exists

      - name: Check for Database Migrations
        run: |
          cd IdRecette_Back_Symfony
          php bin/console doctrine:migrations:status
          if [ $? -eq 0 ]; then
            echo "Database migrations are up-to-date."
          else
            echo "Running database migrations..."
            php bin/console doctrine:migrations:migrate --no-interaction
          fi

      - name: Run Symfony Cache Clear
        run: |
          cd IdRecette_Back_Symfony
          php bin/console cache:clear

      - name: Run Symfony Tests
        run: |
          cd IdRecette_Back_Symfony
          php bin/console doctrine:schema:validate

      - name: Run PHPUnit Tests
        run: |
          cd IdRecette_Back_Symfony
          ./vendor/bin/phpunit --testsuite=Unit
