name: Symfony CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: idrecette_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xml, ctype, iconv, pdo, pdo_mysql, tokenizer, json
          coverage: xdebug

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Backend Dependencies
        working-directory: IdRecette_Back_Symfony
        run: composer install --no-progress --prefer-dist

      - name: Create Database
        working-directory: IdRecette_Back_Symfony
        run: |
          php bin/console --env=test doctrine:database:create --if-not-exists
          php bin/console --env=test doctrine:schema:create

      - name: Run Database Migrations
        working-directory: IdRecette_Back_Symfony
        run: |
          php bin/console --env=test doctrine:migrations:migrate --no-interaction --allow-no-migration

      - name: Clear Cache
        working-directory: IdRecette_Back_Symfony
        run: php bin/console cache:clear --env=test

      - name: Validate Schema
        working-directory: IdRecette_Back_Symfony
        run: php bin/console doctrine:schema:validate --skip-sync

      - name: Run PHPUnit Tests
        working-directory: IdRecette_Back_Symfony
        run: ./vendor/bin/phpunit --coverage-text