name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Navigate to Angular project directory
        run: cd IdRecette_Front

      - name: Install dependencies
        run: |
          cd IdRecette_Front
          npm install

      - name: Build the Angular application
        run: |
          cd IdRecette_Front
          npm run build --prod

      - name: Run tests
        run: |
          cd IdRecette_Front
          npm test -- --watch=false
